<?php
/**
 * Context API implementations
 */
include_once('cmtls_map.contexts.inc');

/**
 * Context API implementations
 */
include_once('cmtls_map.views.inc');

/**
 * Implementation of hook_ctools_plugin_api().
 */
function cmtls_map_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
}

/**
 * Implementation of hook_views_api().
 */
function cmtls_map_views_api() {
  list($module, $api) = func_get_args();
  if ($module == "views" && $api == "views_default") {
    return array("version" => "3.0");
  }
}

/**
 * Implements hook_cmtls_app
 * 
 * @see cmtls.module
 */
function cmtls_map_cmtls_app() {
  return array(
    'cmtls_map' => array(
      'title' => t('Map'),
      'description' => t('Group content on a map'),
    ),
  );
}

